name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run unit tests
      run: npm run test -- --run

    - name: Build project
      run: npm run build
      env:
        NEXT_PUBLIC_SANITY_PROJECT_ID: demo-project
        NEXT_PUBLIC_SANITY_DATASET: production
        NEXT_PUBLIC_SITE_URL: https://gabriel-castro-portfolio.vercel.app

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm run e2e
      env:
        NEXT_PUBLIC_SANITY_PROJECT_ID: demo-project
        NEXT_PUBLIC_SANITY_DATASET: production
        NEXT_PUBLIC_SITE_URL: https://gabriel-castro-portfolio.vercel.app

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30